#!/bin/bash

docker run --rm repronim/neurodocker:latest generate docker \
    --pkg-manager apt \
    --base-image debian:bullseye-slim \
    --yes \
    --fsl version=6.0.7.8 \
    --afni \
> neurodockerbase.Dockerfile

#    --miniconda \
#        version=latest \
#        mamba=true \
#        env_name=neuro \
#        conda_install="python=3.12" \
#        pip_install="s3fs awscli" \
#git clone https://github.com/lncd/lncdtools
