#!/bin/bash

docker run --rm repronim/neurodocker:latest generate docker \
    --pkg-manager apt \
    --base-image debian:bullseye-slim \
    --yes \
    --fsl version=6.0.7.8 \
    --ants version=2.4.3 \
> neurodockerbase.Dockerfile

    #--miniconda \
    #    version=latest \
    #    env_name=neuro \
    #    env_exists=false \
    #    conda_install=pandas \
    #    pip_install=scipy \
#git clone https://github.com/lncd/lncdtools
